# Generated by Django 2.2 on 2019-04-09 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kropboxuser',
            old_name='username',
            new_name='name',
        ),
    ]
